apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finance-api
  name: finance-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-api
  template:
    metadata:
      labels:
        app: finance-api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '80'
    spec:
      containers:
        - name: finance-api
          image: financesregistry.azurecr.io/finance-api:140
          livenessProbe:
            httpGet:
              port: 80
              path: /health
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          ports:
            - containerPort: 80
      imagePullSecrets: 
        - name: regcred
