version: '3'

services:
    finance:
        image: finance-api
        build:
            context: .
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        networks: 
            - finance_network
            
    mssql:
        container_name: finance-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        volumes:
            - ./.docker/data:/var/opt/mssql/data
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=@docker@2021
        ports:
            - "1433:1433"
        networks: 
            - finance_network

networks: 
    finance_network:
        driver: bridge